### ISSUE TITLE
Auth screen's container is messed up on mobile devices

### ISSUE THREAD

**Issue by Perdixius** [Emposoft/EW#14]
Container on auth screen is not centered due to the margins for desktops. Will look into a fix later.

**Comment by AJDev77** [comment]
@javathunderman Ummm, what is the status on this issue?

**Comment by javathunderman** [comment]
Not my problem. @Perdixius is working on this, since it is the Promethean version. I’m working on anything labeled “master”.

**Comment by javathunderman** [comment]
@Perdixius Closing this because of focus on EM and other stuff. Feel free to reopen.
