### ISSUE TITLE
Not the same license

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/EW#17]
Either you need to use the same license as the master or you need to make it explicit that you're a branch or EW that is not affiliated with the master branch and is licensed differently.

**Comment by javathunderman** [comment]
Fixed with latest Promethean commit. 

No more a nooooooob, @Perdixius

**Comment by Perdixius** [comment]
not really @javathunderman, all of the individual files are marked with a different license then the one you changed it to, same thing with EM which you should've contacted me before changing something with the license.

**Comment by javathunderman** [comment]
@Perdixius It doesn't matter- the license terms were the same no matter if we use the MIT or the Creative Commons one we were using before. Besides, Creative Commons is something that we're not supposed to use for code.
