### ISSUE TITLE
Teacher data

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/EW#18]
We need teacher data from student information, however, this is probably something to go with the first stable release, especially since we're building quiz checks (#15) and CPLib (#8).

**Comment by javathunderman** [comment]
@AJDev77 Need some help with this.

**Comment by javathunderman** [comment]
@Perdixius You've had some experience w/ PHPMyAdmin; do you know how to grant access to particular tables for particular users?

**Comment by AJDev77** [comment]
@javathunderman what do you need help with?

**Comment by javathunderman** [comment]
Never mind, pinged @Perdixius for this one.

**Comment by Rythix** [comment]
You can easily do this when you initialize the session and just put the teacher's allowed tables and just displaying user friendly names for the tables.=

**Comment by javathunderman** [comment]
This is stupid, but how do you do that?

**Comment by AJDev77** [comment]
@javathunderman do you mean have specific users access specific databases, or specific users can access specific tables on one database?

**Comment by javathunderman** [comment]
The latter. We have one, big MySQL DB, with tons of little tables for a class by class basis (I don't expect entire schools to pick this up), with each variable being a student and their scores.

**Comment by AJDev77** [comment]
@javathunderman Try this: http://stackoverflow.com/questions/9780637/how-can-i-restrict-a-mysql-user-to-a-particular-tables

**Comment by javathunderman** [comment]
@AJDev77 Looking into this.

**Comment by javathunderman** [comment]
Yay, fixed!
