### ISSUE TITLE
Getting EW back online

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/EW#21]
Currently, EW's beta is running on a Codio server. This is fine for HTML and JS, but MySQL is failing because I cannot properly install PHP and MySQL. Myself+ @AJDev77 are working on this.

**Comment by AJDev77** [comment]
@javathunderman You are going to need to give me the latest build so I can put it up on the VPS. Let's meet up on a call to do this.

**Comment by javathunderman** [comment]
Is this online?

**Comment by AJDev77** [comment]
@javathunderman Yup. Seems to be working on my phone. I think we can close this?

**Comment by javathunderman** [comment]
Yep.

**Comment by javathunderman** [comment]
Reopening and opening issue #27

**Comment by javathunderman** [comment]
Should be OK.

**Comment by javathunderman** [comment]
Reopening once more- couldn't do this because server was down.
